#!/usr/bin/env python3

# Read the file
with open('app/src/main/java/app/familygem/Diagram.java', 'r') as f:
    lines = f.readlines()

# Find line numbers
result_lines = []
added_handler = False
added_methods = False

for i, line in enumerate(lines):
    result_lines.append(line)
    
    # Add handler after Toast.makeText(getContext(), R.string.jpeg_exported_ok, Toast.LENGTH_LONG).show();
    if not added_handler and 'R.string.jpeg_exported_ok' in line and 'Toast.makeText' in line:
        result_lines.append('\t\t\t} // Export diagram to Text\n')
        result_lines.append('\t\t\telse if( requestCode == 906 ) {\n')
        result_lines.append('\t\t\t\tUri uri = data.getData();\n')
        result_lines.append('\t\t\t\ttry {\n')
        result_lines.append('\t\t\t\t\tString textContent = generateFamilyTreeText();\n')
        result_lines.append('\t\t\t\t\tOutputStream out = getContext().getContentResolver().openOutputStream(uri, "wt");\n')
        result_lines.append('\t\t\t\t\tout.write(textContent.getBytes("UTF-8"));\n')
        result_lines.append('\t\t\t\t\tout.flush();\n')
        result_lines.append('\t\t\t\t\tout.close();\n')
        result_lines.append('\t\t\t\t\tToast.makeText(getContext(), R.string.text_exported_ok, Toast.LENGTH_LONG).show();\n')
        result_lines.append('\t\t\t\t} catch( Exception e ) {\n')
        result_lines.append('\t\t\t\t\tToast.makeText(getContext(), e.getLocalizedMessage(), Toast.LENGTH_LONG).show();\n')
        result_lines.append('\t\t\t\t}\n')
        added_handler = True
        
    # Add methods before private void openSubtree(Person personConnector) {
    if not added_methods and 'private void openSubtree(Person personConnector)' in line:
        # Add the new methods before this line
        result_lines.pop()  # Remove the line we just added
        result_lines.append('\t/**\n')
        result_lines.append('\t * Share diagram as Text through Android share sheet\n')
        result_lines.append('\t */\n')
        result_lines.append('\tprivate void shareDiagramAsText() {\n')
        result_lines.append('\t\ttry {\n')
        result_lines.append('\t\t\t// Generate text representation\n')
        result_lines.append('\t\t\tString textContent = generateFamilyTreeText();\n')
        result_lines.append('\n')
        result_lines.append('\t\t\t// Write Text to temp file\n')
        result_lines.append('\t\t\tFile cacheDir = new File(getContext().getCacheDir(), "shared");\n')
        result_lines.append('\t\t\tcacheDir.mkdirs();\n')
        result_lines.append('\t\t\tString treeTitle = Global.settings.getTree(Global.settings.openTree).title.replaceAll("[\\$\\']", "_");\n')
        result_lines.append('\t\t\tFile textFile = new File(cacheDir, treeTitle + ".txt");\n')
        result_lines.append('\t\t\t\n')
        result_lines.append('\t\t\tFileOutputStream fos = new FileOutputStream(textFile);\n')
        result_lines.append('\t\t\tfos.write(textContent.getBytes("UTF-8"));\n')
        result_lines.append('\t\t\tfos.flush();\n')
        result_lines.append('\t\t\tfos.close();\n')
        result_lines.append('\n')
        result_lines.append('\t\t\t// Get URI and share\n')
        result_lines.append('\t\t\tUri textUri = androidx.core.content.FileProvider.getUriForFile(\n')
        result_lines.append('\t\t\t\t\tgetContext(),\n')
        result_lines.append('\t\t\t\t\tgetContext().getPackageName() + ".provider",\n')
        result_lines.append('\t\t\t\t\ttextFile);\n')
        result_lines.append('\n')
        result_lines.append('\t\t\tIntent shareIntent = new Intent(Intent.ACTION_SEND);\n')
        result_lines.append('\t\t\tshareIntent.setType("text/plain");\n')
        result_lines.append('\t\t\tshareIntent.putExtra(Intent.EXTRA_STREAM, textUri);\n')
        result_lines.append('\t\t\tshareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);\n')
        result_lines.append('\t\t\tstartActivity(Intent.createChooser(shareIntent, getText(R.string.share_diagram)));\n')
        result_lines.append('\n')
        result_lines.append('\t\t} catch (Exception e) {\n')
        result_lines.append('\t\t\tToast.makeText(getContext(), e.getLocalizedMessage(), Toast.LENGTH_LONG).show();\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t}\n')
        result_lines.append('\n')
        result_lines.append('\t/**\n')
        result_lines.append('\t * Generate text representation of the family tree\n')
        result_lines.append('\t */\n')
        result_lines.append('\tprivate String generateFamilyTreeText() {\n')
        result_lines.append('\t\tStringBuilder sb = new StringBuilder();\n')
        result_lines.append('\t\tSettings.Tree tree = Global.settings.getTree(Global.settings.openTree);\n')
        result_lines.append('\t\tsb.append(tree.title).append("\\n");\n')
        result_lines.append('\t\t// Create equals line (Java 8 compatible)\n')
        result_lines.append('\t\tfor (int i = 0; i < tree.title.length(); i++) {\n')
        result_lines.append('\t\t\tsb.append("=");\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t\tsb.append("\\n\\n");\n')
        result_lines.append('\n')
        result_lines.append('\t\t// Start from the current person (fulcrum)\n')
        result_lines.append('\t\tPerson fulcrumPerson = gc.getPerson(Global.indi);\n')
        result_lines.append('\t\tif (fulcrumPerson != null) {\n')
        result_lines.append('\t\t\tsb.append(getString(R.string.diagram_of)).append(": ");\n')
        result_lines.append('\t\t\tsb.append(U.epiteto(fulcrumPerson)).append("\\n\\n");\n')
        result_lines.append('\t\t\tgenerateFamilyTreeTextRecursive(fulcrumPerson, sb, 0, new java.util.HashSet<String>());\n')
        result_lines.append('\t\t} else {\n')
        result_lines.append('\t\t\tsb.append(getString(R.string.no_persons)).append("\\n");\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\n')
        result_lines.append('\t\treturn sb.toString();\n')
        result_lines.append('\t}\n')
        result_lines.append('\n')
        result_lines.append('\t/**\n')
        result_lines.append('\t * Recursively generate text representation of family members\n')
        result_lines.append('\t */\n')
        result_lines.append('\tprivate void generateFamilyTreeTextRecursive(Person person, StringBuilder sb, int level, Set<String> visited) {\n')
        result_lines.append('\t\tif (person == null || visited.contains(person.getId())) {\n')
        result_lines.append('\t\t\treturn;\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t\tvisited.add(person.getId());\n')
        result_lines.append('\n')
        result_lines.append('\t\t// Create indentation (Java 8 compatible)\n')
        result_lines.append('\t\tStringBuilder indentBuilder = new StringBuilder();\n')
        result_lines.append('\t\tfor (int i = 0; i < level; i++) {\n')
        result_lines.append('\t\t\tindentBuilder.append("  ");\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t\tString indent = indentBuilder.toString();\n')
        result_lines.append('\n')
        result_lines.append('\t\t// Person info\n')
        result_lines.append('\t\tsb.append(indent);\n')
        result_lines.append('\t\tif (level > 0) {\n')
        result_lines.append('\t\t\tsb.append("\u251c\u2500 "); // \u251c\u2500\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t\tsb.append(U.epiteto(person));\n')
        result_lines.append('\n')
        result_lines.append('\t\t// Birth and death dates\n')
        result_lines.append('\t\tString dates = U.twoDates(person, false);\n')
        result_lines.append('\t\tif (dates != null && !dates.isEmpty()) {\n')
        result_lines.append('\t\t\tsb.append(" (").append(dates).append(")");\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t\tsb.append("\\n");\n')
        result_lines.append('\n')
        result_lines.append('\t\t// Spouses and children\n')
        result_lines.append('\t\tList<Family> spouseFamilies = person.getSpouseFamilies(gc);\n')
        result_lines.append('\t\tif (spouseFamilies != null) {\n')
        result_lines.append('\t\t\tfor (Family family : spouseFamilies) {\n')
        result_lines.append('\t\t\t\t// Find spouse\n')
        result_lines.append('\t\t\t\tPerson spouse = null;\n')
        result_lines.append('\t\t\t\tif (family.getHusbandRefs() != null && person.getSpouseFamilyRefs() != null) {\n')
        result_lines.append('\t\t\t\t\tfor (org.folg.gedcom.model.SpouseFamilyRef ref : person.getSpouseFamilyRefs()) {\n')
        result_lines.append('\t\t\t\t\t\tif (ref.getRef().equals(family.getId())) {\n')
        result_lines.append('\t\t\t\t\t\t\tfor (org.folg.gedcom.model.SpouseRef husbandRef : family.getHusbandRefs()) {\n')
        result_lines.append('\t\t\t\t\t\t\t\tPerson husband = gc.getPerson(husbandRef.getRef());\n')
        result_lines.append('\t\t\t\t\t\t\t\tif (husband != null && !husband.getId().equals(person.getId())) {\n')
        result_lines.append('\t\t\t\t\t\t\t\t\tspouse = husband;\n')
        result_lines.append('\t\t\t\t\t\t\t\t\tbreak;\n')
        result_lines.append('\t\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t}\n')
        result_lines.append('\t\t\t\tif (spouse == null && family.getWifeRefs() != null && person.getSpouseFamilyRefs() != null) {\n')
        result_lines.append('\t\t\t\t\tfor (org.folg.gedcom.model.SpouseFamilyRef ref : person.getSpouseFamilyRefs()) {\n')
        result_lines.append('\t\t\t\t\t\tif (ref.getRef().equals(family.getId())) {\n')
        result_lines.append('\t\t\t\t\t\t\tfor (org.folg.gedcom.model.SpouseRef wifeRef : family.getWifeRefs()) {\n')
        result_lines.append('\t\t\t\t\t\t\t\tPerson wife = gc.getPerson(wifeRef.getRef());\n')
        result_lines.append('\t\t\t\t\t\t\t\tif (wife != null && !wife.getId().equals(person.getId())) {\n')
        result_lines.append('\t\t\t\t\t\t\t\t\tspouse = wife;\n')
        result_lines.append('\t\t\t\t\t\t\t\t\tbreak;\n')
        result_lines.append('\t\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t}\n')
        result_lines.append('\n')
        result_lines.append('\t\t\t\tif (spouse != null && !visited.contains(spouse.getId())) {\n')
        result_lines.append('\t\t\t\t\tsb.append(indent).append("  ");\n')
        result_lines.append('\t\t\t\t\tsb.append("\u26ad ").append(U.epiteto(spouse)); // \u26ad\n')
        result_lines.append('\t\t\t\t\tString spouseDates = U.twoDates(spouse, false);\n')
        result_lines.append('\t\t\t\t\tif (spouseDates != null && !spouseDates.isEmpty()) {\n')
        result_lines.append('\t\t\t\t\t\tsb.append(" (").append(spouseDates).append(")");\n')
        result_lines.append('\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\tsb.append("\\n");\n')
        result_lines.append('\t\t\t\t}\n')
        result_lines.append('\n')
        result_lines.append('\t\t\t\t// Children\n')
        result_lines.append('\t\t\t\tif (family.getChildRefs() != null) {\n')
        result_lines.append('\t\t\t\t\tfor (org.folg.gedcom.model.ChildRef childRef : family.getChildRefs()) {\n')
        result_lines.append('\t\t\t\t\t\tPerson child = gc.getPerson(childRef.getRef());\n')
        result_lines.append('\t\t\t\t\t\tif (child != null && !visited.contains(child.getId())) {\n')
        result_lines.append('\t\t\t\t\t\t\tgenerateFamilyTreeTextRecursive(child, sb, level + 1, visited);\n')
        result_lines.append('\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t}\n')
        result_lines.append('\t\t\t}\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\n')
        result_lines.append('\t\t// Parents (only for the root person)\n')
        result_lines.append('\t\tif (level == 0 && person.getParentFamilyRefs() != null) {\n')
        result_lines.append('\t\t\tfor (org.folg.gedcom.model.ParentFamilyRef parentFamilyRef : person.getParentFamilyRefs()) {\n')
        result_lines.append('\t\t\t\tFamily parentFamily = gc.getFamily(parentFamilyRef.getRef());\n')
        result_lines.append('\t\t\t\tif (parentFamily != null) {\n')
        result_lines.append('\t\t\t\t\tsb.append("\\n").append(getString(R.string.parents)).append(":\\n");\n')
        result_lines.append('\t\t\t\t\t\n')
        result_lines.append('\t\t\t\t\t// Father\n')
        result_lines.append('\t\t\t\t\tif (parentFamily.getHusbandRefs() != null) {\n')
        result_lines.append('\t\t\t\t\t\tfor (org.folg.gedcom.model.SpouseRef husbandRef : parentFamily.getHusbandRefs()) {\n')
        result_lines.append('\t\t\t\t\t\t\tPerson father = gc.getPerson(husbandRef.getRef());\n')
        result_lines.append('\t\t\t\t\t\t\tif (father != null) {\n')
        result_lines.append('\t\t\t\t\t\t\t\tsb.append("  \u251c\u2500 ").append(getString(R.string.father)).append(": ");\n')
        result_lines.append('\t\t\t\t\t\t\t\tsb.append(U.epiteto(father));\n')
        result_lines.append('\t\t\t\t\t\t\t\tString fatherDates = U.twoDates(father, false);\n')
        result_lines.append('\t\t\t\t\t\t\t\tif (fatherDates != null && !fatherDates.isEmpty()) {\n')
        result_lines.append('\t\t\t\t\t\t\t\t\tsb.append(" (").append(fatherDates).append(")");\n')
        result_lines.append('\t\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t\t\tsb.append("\\n");\n')
        result_lines.append('\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\n')
        result_lines.append('\t\t\t\t\t// Mother\n')
        result_lines.append('\t\t\t\t\tif (parentFamily.getWifeRefs() != null) {\n')
        result_lines.append('\t\t\t\t\t\tfor (org.folg.gedcom.model.SpouseRef wifeRef : parentFamily.getWifeRefs()) {\n')
        result_lines.append('\t\t\t\t\t\t\tPerson mother = gc.getPerson(wifeRef.getRef());\n')
        result_lines.append('\t\t\t\t\t\t\tif (mother != null) {\n')
        result_lines.append('\t\t\t\t\t\t\t\tsb.append("  \u251c\u2500 ").append(getString(R.string.mother)).append(": ");\n')
        result_lines.append('\t\t\t\t\t\t\t\tsb.append(U.epiteto(mother));\n')
        result_lines.append('\t\t\t\t\t\t\t\tString motherDates = U.twoDates(mother, false);\n')
        result_lines.append('\t\t\t\t\t\t\t\tif (motherDates != null && !motherDates.isEmpty()) {\n')
        result_lines.append('\t\t\t\t\t\t\t\t\tsb.append(" (").append(motherDates).append(")");\n')
        result_lines.append('\t\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t\t\tsb.append("\\n");\n')
        result_lines.append('\t\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t\t}\n')
        result_lines.append('\t\t\t\t}\n')
        result_lines.append('\t\t\t}\n')
        result_lines.append('\t\t}\n')
        result_lines.append('\t}\n')
        result_lines.append('\n')
        result_lines.append(line)  # Add the openSubtree line back
        added_methods = True

# Write result
with open('app/src/main/java/app/familygem/Diagram.java', 'w') as f:
    f.writelines(result_lines)

print(f'Added handler: {added_handler}')
print(f'Added methods: {added_methods}')
